#include "gemini_protocol.h"
#include "gemini_message.h"
#include "web_config.h"
#include "cJSON.h"
#include "esp_log.h"
#include <stdlib.h>
#include <string.h>
static const char*TAG="GEMINI_PROTO";
static constexpr char AUDIO_MIME[]="audio/pcm;rate=16000";
static char s_session_handle[512]={0};
static size_t b64size(size_t n){return ((n+2U)/3U)*4U;}
static bool b64(const uint8_t*i,size_t n,char*o,size_t z){static const char T[]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";if(!i||!o||z<b64size(n)+1)return false;size_t a=0,b=0;while(a+2<n){uint32_t v=((uint32_t)i[a]<<16)|((uint32_t)i[a+1]<<8)|i[a+2];o[b++]=T[(v>>18)&63];o[b++]=T[(v>>12)&63];o[b++]=T[(v>>6)&63];o[b++]=T[v&63];a+=3;}size_t r=n-a;if(r==1){uint32_t v=(uint32_t)i[a]<<16;o[b++]=T[(v>>18)&63];o[b++]=T[(v>>12)&63];o[b++]='=';o[b++]='=';}else if(r==2){uint32_t v=((uint32_t)i[a]<<16)|((uint32_t)i[a+1]<<8);o[b++]=T[(v>>18)&63];o[b++]=T[(v>>12)&63];o[b++]=T[(v>>6)&63];o[b++]='=';}o[b]=0;return true;}
bool gemini_protocol_build_setup(char**output,size_t*output_len){if(!output||!output_len)return false;*output=nullptr;*output_len=0;cJSON*root=cJSON_CreateObject();if(!root)return false;cJSON*setup=cJSON_AddObjectToObject(root,"setup");cJSON*gen=cJSON_AddObjectToObject(setup,"generationConfig");cJSON*mods=cJSON_AddArrayToObject(gen,"responseModalities");cJSON_AddItemToArray(mods,cJSON_CreateString("AUDIO"));cJSON*speech=cJSON_AddObjectToObject(gen,"speechConfig");cJSON_AddStringToObject(speech,"languageCode","id-ID");cJSON*voice=cJSON_AddObjectToObject(speech,"voiceConfig");cJSON*pre=cJSON_AddObjectToObject(voice,"prebuiltVoiceConfig");cJSON_AddStringToObject(pre,"voiceName","Kore");cJSON_AddStringToObject(setup,"model","models/gemini-3.1-flash-live-preview");cJSON_AddObjectToObject(setup,"inputAudioTranscription");cJSON*instruction=cJSON_AddObjectToObject(setup,"systemInstruction");cJSON*parts=cJSON_AddArrayToObject(instruction,"parts");cJSON*p=cJSON_CreateObject();cJSON_AddStringToObject(p,"text","Kamu adalah asisten suara berbahasa Indonesia. Jawab secara natural, singkat, dan jelas.");cJSON_AddItemToArray(parts,p);char role[2048]={0};if(web_config_load_role(role,sizeof(role))&&role[0]){cJSON*rp=cJSON_CreateObject();cJSON_AddStringToObject(rp,"text",role);cJSON_AddItemToArray(parts,rp);}cJSON*rt=cJSON_AddObjectToObject(setup,"realtimeInputConfig");cJSON*aad=cJSON_AddObjectToObject(rt,"automaticActivityDetection");cJSON_AddBoolToObject(aad,"disabled",false);cJSON_AddStringToObject(aad,"startOfSpeechSensitivity","START_SENSITIVITY_HIGH");cJSON_AddNumberToObject(aad,"prefixPaddingMs",40);cJSON_AddStringToObject(aad,"endOfSpeechSensitivity","END_SENSITIVITY_HIGH");cJSON_AddNumberToObject(aad,"silenceDurationMs",500);cJSON*res=cJSON_AddObjectToObject(setup,"sessionResumption");if(s_session_handle[0])cJSON_AddStringToObject(res,"handle",s_session_handle);char*json=cJSON_PrintUnformatted(root);cJSON_Delete(root);if(!json)return false;*output=json;*output_len=strlen(json);return true;}
bool gemini_protocol_build_realtime_audio(const int16_t*pcm,size_t samples,char**output,size_t*output_len){if(!pcm||!samples||!output||!output_len)return false;size_t bytes=samples*2,n=b64size(bytes);char*enc=(char*)malloc(n+1);if(!enc||!b64((const uint8_t*)pcm,bytes,enc,n+1)){free(enc);return false;}cJSON*r=cJSON_CreateObject();cJSON*rt=r?cJSON_AddObjectToObject(r,"realtimeInput"):nullptr;cJSON*a=rt?cJSON_AddObjectToObject(rt,"audio"):nullptr;if(!a){cJSON_Delete(r);free(enc);return false;}cJSON_AddStringToObject(a,"data",enc);cJSON_AddStringToObject(a,"mimeType",AUDIO_MIME);char*j=cJSON_PrintUnformatted(r);cJSON_Delete(r);free(enc);if(!j)return false;*output=j;*output_len=strlen(j);return true;}
bool gemini_protocol_process_message(const char*json,size_t len){if(!json||!len)return false;cJSON*r=cJSON_ParseWithLength(json,len);if(!r)return false;bool ok=gemini_message_classify(json,len)!=GEMINI_MESSAGE_UNKNOWN;cJSON_Delete(r);return ok;}
